### ISSUE TITLE
NSURLConnection finished with error - code -1100

### ISSUE THREAD

**Issue by jorgemejia** [FazioNico/ionic-ar-placement#3]
Now I have this error NSURLConnection finished with error - code -1100 I don´t know why I hope you can helpme whit this

**Comment by FazioNico** [comment]
Hi! Thank for your interest.
This project is no longer maintain. It runing on a old version of Ionic. Maybe you have to update project to keep the error away.

So can you writ me more detail about printed error from your console?

**Comment by jorgemejia** [comment]
I solve this issue, had to install all via npm each plugin and generate all the providers, now my problem is, I can´t see the locations through the arView, I guess is css problem.
